package com.example.maquetacionapp.commons

const val MIN_NUM_OF_ELEMENTS = 3
const val MAX_NUM_OF_ELEMENTS = 10

const val MIN_NUM_OF_CHARS_PARAGRAPHS = 50
const val MAX_NUM_OF_CHARS_PARAGRAPHS = 400

const val MIN_NUM_OF_CHARS_LAST_PARAGRAPHS = 30
const val MAX_NUM_OF_CHARS_LAST_PARAGRAPHS = 100

const val MIN_NUM_OF_CHARS_ELEMENTS = 10
const val MAX_NUM_OF_CHARS_ELEMENTS = 120

const val MIN_SCALE_TRANSFORMER = 0.85f
const val MIN_ALPHA_TRANSFORMER = 0.5f


